on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrdemo347pzhzb7day6.azurecr.io
        username: ${{ secrets.acr_acrdemo347pzhzb7day6_username }}
        password: ${{ secrets.acr_acrdemo347pzhzb7day6_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acrdemo347pzhzb7day6.azurecr.io/aksdemo347pzhzb7day6:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acrdemo347pzhzb7day6.azurecr.io/aksdemo347pzhzb7day6:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdemo347pzhzb7day6_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-demo347pzhzb7day69634 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-demo347pzhzb7day69634`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-demo347pzhzb7day69634
        container-registry-url: acrdemo347pzhzb7day6.azurecr.io
        container-registry-username: ${{ secrets.acr_acrdemo347pzhzb7day6_username }}
        container-registry-password: ${{ secrets.acr_acrdemo347pzhzb7day6_password }}
        secret-name: aksdemo347pzdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-demo347pzhzb7day69634
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          acrdemo347pzhzb7day6.azurecr.io/aksdemo347pzhzb7day6:${{ github.sha }}
        imagepullsecrets: |
          aksdemo347pzdockerauth
